spring.application.name=movie
spring.profiles.active=dev
server.port=8080
# server.servlet.context-path=/api/v1   // This is bad because it will affect all endpoints, including Swagger UI.


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# DevTools
spring.devtools.restart.enabled=true

#logging
logging.level.org.springframework=WARN
#logging to a file
logging.file.name=logs/movie-app.log

app.jwt.secret=${JWT_SECRET:this-is-the-secret-key-used-to-sign-jwt-tokens-keep-it-safe}

app.jwt.expiration=9000000

