spring.application.name=movie
spring.profiles.active=dev
server.port=8080
# server.servlet.context-path=/api/v1   // This is bad because it will affect all endpoints, including Swagger UI.


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# DevTools
spring.devtools.restart.enabled=true

logging.file.name=logs/app.log
logging.level.org.springframework=WARN

